image: docker:latest
services:
  - docker:dind
stages:
  - build
  - deploy

before_script:
  - docker login --username "$REGISTRY_USER" --password "$REGISTRY_PASS" "$REGISTRY_ADDR"

build-production:
  stage: build
  script:
    - docker build --rm --build-arg VERSION=${CI_COMMIT_SHA:0:8} -t "$REGISTRY_ADDR/$REPO_PATH" -t "$REGISTRY_ADDR/$REPO_PATH:${CI_COMMIT_SHA:0:8}" .
    - docker push "$REGISTRY_ADDR/$REPO_PATH:${CI_COMMIT_SHA:0:8}"
    - docker push "$REGISTRY_ADDR/$REPO_PATH"
  when: manual
  only:
    - master
  tags:
    - builder

deploy-production:
  stage: deploy
  script:
    - echo ${CI_COMMIT_SHA:0:8}
    - export NAFFROPAN_PRODUCTION_TAG=${CI_COMMIT_SHA:0:8}
    - rsync -avH --delete ./stack-production.yml /swarm/shavaz/new-panel/stack-production.yml
    - docker stack deploy --with-registry-auth -c /swarm/shavaz/new-panel/stack-production.yml shavaz-new-panel
  when: manual
  only:
    - master
  tags:
    - deployer
