version: "3.8"
services:

  server:
    image: "registry.mn.nafis.cloud/shavaz/frontend/new-panel:${NAFFROPAN_PRODUCTION_TAG:-latest}"
    networks:
      - shavaz-new-panel
    ports:
      - "5002:5002"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.stateless == true
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"


networks:
  shavaz-new-panel:
    name: shavaz-new-panel
    driver: overlay
    attachable: true
